name: Build and Test

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore Pomnesh
      
    - name: Build
      run: dotnet build --no-restore Pomnesh
      
    - name: Test
      run: dotnet test --no-build --verbosity normal Pomnesh