name: Workflow для развертывания master окружения

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vskydev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . -t vskydev/pomnesh:$(git rev-parse --short "$GITHUB_SHA")
      - name: Push the Docker image
        run: docker push vskydev/pomnesh:$(git rev-parse --short "$GITHUB_SHA")